#!/bin/bash

echo "🔧 Fixing Product Questionnaires..."
echo ""
echo "This script will fix questionnaires that were incorrectly marked as templates."
echo "You need to be logged into the tenant portal to run this."
echo ""
echo "Instructions:"
echo "1. Make sure your backend server is running (patient-api)"
echo "2. Open your browser's Developer Console (F12)"
echo "3. Go to the tenant portal (localhost:3030)"
echo "4. In the console, paste this command:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "fetch('http://localhost:3001/admin/fix-product-questionnaires', {"
echo "  method: 'POST',"
echo "  headers: {"
echo "    'Authorization': 'Bearer ' + localStorage.getItem('token'),"
echo "    'Content-Type': 'application/json'"
echo "  }"
echo "}).then(r => r.json()).then(d => console.log('✅ Result:', d))"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "5. Press Enter to execute"
echo "6. You should see: ✅ Result: {success: true, message: 'Fixed X product questionnaires'}"
echo ""
echo "After running this, reload your product pages!"
echo ""


