packages:
  - patient-api/
  - patient-frontend/
  - fuse-admin-frontend/
  - fuse-tenant-portal-frontend/
  - packages/*
  
catalog:
  # Build & Development Tools
  typescript: ^5.9.2
  "@types/node": ^24.3.0
  concurrently: ^9.2.0
  cspell: ^9.1.1
  dotenv: ^16.5.0
  dotenv-cli: ^8.0.0
  eslint: ^9.29.0
  prettier: ^3.6.0

  # CSS & Styling
  autoprefixer: ^10.4.21
  postcss: ^8.5.6
  tailwindcss: ^4.1.12
  tailwind-merge: ^3.3.1
  tailwindcss-animate: ^1.0.7

  # UI Components - Radix UI
  "@radix-ui/react-accordion": 1.2.2
  "@radix-ui/react-alert-dialog": 1.1.4
  "@radix-ui/react-aspect-ratio": 1.1.1
  "@radix-ui/react-avatar": 1.1.2
  "@radix-ui/react-checkbox": 1.1.3
  "@radix-ui/react-collapsible": 1.1.2
  "@radix-ui/react-context-menu": 2.2.4
  "@radix-ui/react-dialog": 1.1.4
  "@radix-ui/react-dropdown-menu": 2.1.4
  "@radix-ui/react-hover-card": 1.1.4
  "@radix-ui/react-label": 2.1.1
  "@radix-ui/react-menubar": 1.1.4
  "@radix-ui/react-navigation-menu": 1.2.3
  "@radix-ui/react-popover": 1.1.4
  "@radix-ui/react-progress": 1.1.1
  "@radix-ui/react-radio-group": 1.2.2
  "@radix-ui/react-scroll-area": 1.2.2
  "@radix-ui/react-select": 2.1.4
  "@radix-ui/react-separator": 1.1.1
  "@radix-ui/react-slider": 1.2.2
  "@radix-ui/react-slot": 1.1.1
  "@radix-ui/react-switch": 1.1.2
  "@radix-ui/react-tabs": 1.1.2
  "@radix-ui/react-toast": 1.2.4
  "@radix-ui/react-toggle": 1.1.1
  "@radix-ui/react-toggle-group": 1.1.1
  "@radix-ui/react-tooltip": 1.1.6

  # UI Components - Other
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: 1.0.4
  embla-carousel-react: 8.5.1
  input-otp: 1.4.1
  lucide-react: ^0.454.0
  vaul: ^0.9.9

  # Forms & Validation
  "@hookform/resolvers": ^3.10.0
  react-hook-form: ^7.60.0
  zod: 3.25.67

  # Date & Time
  date-fns: 4.1.0
  react-day-picker: 9.8.0

  # UI Utilities
  next-themes: ^0.4.6
  react-resizable-panels: ^2.1.7
  sonner: ^1.7.4

  # Charts
  recharts: 2.15.4

  # Analytics
  "@vercel/analytics": 1.3.1

  # Authentication & Security
  "@types/jsonwebtoken": ^9.0.10
  jsonwebtoken: ^9.0.2
  
  # Turbo
  '@turbo/gen': ^2.5.4
  turbo: ^2.5.4



catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.18
    "@types/react-dom": ^18.3.5

  react19:
    react: ^19.1.1
    react-dom: ^19.1.1
    "@types/react": 19.1.12

  next14:
    next: 14.2.25

  next15:
    next: 15.5.2

